services:
  app:
    build: .
    restart: always
    container_name: app-social-network
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
  mongo: 
    image: mongo
    restart: always
    env_file:
      - .env
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - $DB_PORT:${DB_PORT}